name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK cmdline-tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q tools.zip -d .
          rm tools.zip
          mv cmdline-tools latest   # rinomina la cartella
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/android-sdk/build-tools/33.0.2" >> $GITHUB_PATH
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip python3-setuptools python3-wheel \
            git zip unzip openjdk-17-jdk \
            libffi-dev libssl-dev liblzma-dev zlib1g-dev libjpeg-dev libfreetype6-dev

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install buildozer and python deps
        run: |
          python3 -m pip install --user buildozer cython virtualenv kivy kivymd reportlab pillow

      - name: Build APK (debug)
        env:
          ANDROIDAPI: "33"
          NDKAPI: "21"
          ANDROID_SDK_ROOT: $HOME/android-sdk
          PATH: $HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/build-tools/33.0.2:$HOME/.local/bin:$PATH
        run: |
          /usr/bin/python3 -m buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: mealapp-apk
          path: bin/*.apk
