name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK cmdline-tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip tools.zip
          mv cmdline-tools latest
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk \
            libffi-dev libssl-dev liblzma-dev zlib1g-dev libjpeg-dev libfreetype6-dev

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install buildozer and python deps
        run: |
          python3 -m pip install buildozer cython pillow kivy kivymd reportlab

      - name: Build APK (debug)
        env:
          ANDROIDAPI: "33"
          NDKAPI: "21"
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          PATH: $ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/build-tools/33.0.2:$HOME/.local/bin:$PATH
        run: |
          python -m buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: mealapp-apk
          path: bin/*.apk
